# Generated by Django 4.2.1 on 2023-05-26 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0003_alter_rockets_bdf_start_rocket'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='data_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t',
            field=models.DecimalField(decimal_places=3, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='start_rocket',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='text',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
