# Generated by Django 4.2.1 on 2023-05-26 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0004_rockets_bdf_data_added_rockets_bdf_t_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='L',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='L_Kon',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=4),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='d0',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='d0_Kon',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=3),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='tol_Kon',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='tol_R',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=5),
            preserve_default=False,
        ),
    ]
