# Generated by Django 4.2.1 on 2023-05-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0005_rockets_bdf_l_rockets_bdf_l_kon_rockets_bdf_d0_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rockets_bdf',
            name='tol_Kon',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='tol_R',
            field=models.DecimalField(decimal_places=3, max_digits=4),
        ),
    ]
