# Generated by Django 4.2.1 on 2023-05-29 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0006_alter_rockets_bdf_tol_kon_alter_rockets_bdf_tol_r'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='X1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X4',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X5',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='kolichestvo_amort',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='zhestkost_amort',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
    ]
