# Generated by Django 4.2.1 on 2023-05-29 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0007_rockets_bdf_x1_rockets_bdf_x2_rockets_bdf_x3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='P0',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P1',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P10',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P11',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P12',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P13',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P5',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P6',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P7',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P8',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='P9',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='V_sredy',
            field=models.DecimalField(decimal_places=1, default=1, help_text='м/с', max_digits=5),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='dl_1',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='dl_2',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='dl_3',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='nap_zak_1',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='nap_zak_2',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='nap_zak_3',
            field=models.PositiveSmallIntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p0',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p10',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p11',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p12',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p13',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p2',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p3',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p4',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p5',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p6',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p7',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p8',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='t_p9',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='zhestkost_opor_1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='zhestkost_opor_2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='zhestkost_opor_3',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
