# Generated by Django 4.2.1 on 2023-05-30 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0008_rockets_bdf_p0_rockets_bdf_p1_rockets_bdf_p10_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='Lg_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Lo_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_cy',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_dy_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='X_gch',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Xg_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='Xo_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='koeff_puass1',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='koeff_puass2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_cy',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_dy_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='m_gch',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='mg_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='mo_1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='modul_unga1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='modul_unga2',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='plotnost2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='nap_zak_1',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='nap_zak_2',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='nap_zak_3',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
