# Generated by Django 4.2.2 on 2023-06-14 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0010_rockets_bdf_n_alter_rockets_bdf_v_sredy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='N',
        ),
    ]
