# Generated by Django 4.2.2 on 2023-06-14 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0011_remove_rockets_bdf_n'),
    ]

    operations = [
        migrations.AddField(
            model_name='rockets_bdf',
            name='a1',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='a2',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='a3',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='a4',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rockets_bdf',
            name='a5',
            field=models.DecimalField(decimal_places=1, default=1, max_digits=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='P0',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='t_p0',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6),
        ),
    ]
