# Generated by Django 4.2.2 on 2023-06-21 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bdf', '0014_rename_a1_rockets_bdf_l_kon_zakr_1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='P0',
        ),
        migrations.RemoveField(
            model_name='rockets_bdf',
            name='t_p0',
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='P2',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rockets_bdf',
            name='t_p2',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=6),
            preserve_default=False,
        ),
    ]
